# Generated by Django 6.0 on 2026-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration',
            field=models.CharField(default='yearly', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=50, unique=True),
        ),
    ]
