# Generated by Django 6.0 on 2026-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_duration_alter_membership_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='Company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('agent', 'Real Estate Agent'), ('broker', 'Broker'), ('escrow', 'Escrow / Title'), ('lender', 'Lender'), ('appraiser', 'Appraiser'), ('investor', 'Investor'), ('enterprise', 'Enterprise'), ('other', 'Other')], default='Role', max_length=20),
            preserve_default=False,
        ),
    ]
