# Generated by Django 6.0 on 2026-03-26 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_email_token_userprofile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
