# Generated by Django 6.0 on 2026-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportresult',
            old_name='median_new_listing_price',
            new_name='median_price_new_listings',
        ),
        migrations.RemoveField(
            model_name='reportresult',
            name='market_action_index',
        ),
        migrations.RemoveField(
            model_name='reportresult',
            name='market_type',
        ),
        migrations.AddField(
            model_name='reportresult',
            name='market_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
