# Generated by Django 6.0 on 2026-04-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_median_new_listing_price_reportresult_median_price_new_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresult',
            name='market_action',
        ),
    ]
